<?php
require_once __DIR__.'/includes/functions.php'; verify_csrf(); $pdo=db();
if(!isset($_SESSION['captcha'])) $_SESSION['captcha']=(string)random_int(10000,99999);
if(isset($_POST['refresh_captcha'])){$_SESSION['captcha']=(string)random_int(10000,99999);header('Location: /');exit;}
if(isset($_POST['send_otp'])){$phone=trim($_POST['phone']);$name=trim($_POST['full_name']);$tn=trim($_POST['transfer_number']);$cap=trim($_POST['captcha']);
if(!is_valid_phone($phone)) flash('err','رقم الهاتف 09xxxxxxxx'); elseif(!is_valid_full_name($name)) flash('err','الاسم أحرف فقط'); elseif(!is_valid_transfer_number($tn)) flash('err','رقم الحوالة english alnum only'); elseif($cap!==($_SESSION['captcha']??'')) flash('err','كابتشا خاطئة'); else {$otp=(string)random_int(1000,9999);$pdo->prepare('INSERT INTO otp_codes (phone,full_name,code,transfer_number,expires_at,used,created_at) VALUES (?,?,?,?,DATE_ADD(NOW(),INTERVAL 5 MINUTE),0,NOW())')->execute([$phone,$name,$otp,$tn]);$_SESSION['pending']=['branch_id'=>(int)$_POST['branch_id'],'company_id'=>(int)$_POST['company_id'],'booking_date'=>$_POST['booking_date'],'slot_time'=>$_POST['slot_time'],'phone'=>$phone,'full_name'=>$name,'transfer_number'=>$tn];flash('ok','OTP للتجربة: '.$otp);} header('Location: /');exit;}
if(isset($_POST['confirm_booking'])){$p=$_SESSION['pending']??null;$otp=trim($_POST['otp_code']??'');if(!$p) flash('err','ابدأ الطلب أولاً'); elseif(!booking_date_allowed($p['booking_date'])) flash('err','الحجز من الغد فقط'); elseif(is_holiday($p['booking_date'])) flash('err','هذا اليوم عطلة'); else {$day=date('l',strtotime($p['booking_date']));$d=$pdo->prepare('SELECT * FROM business_days WHERE branch_id=? AND day_name=? AND active=1');$d->execute([$p['branch_id'],$day]);$cfg=$d->fetch();if(!$cfg) flash('err','اليوم غير متاح'); else {$oc=$pdo->prepare('SELECT * FROM otp_codes WHERE phone=? AND transfer_number=? AND code=? AND used=0 ORDER BY id DESC LIMIT 1');$oc->execute([$p['phone'],$p['transfer_number'],$otp]);$or=$oc->fetch(); if(!$or) flash('err','OTP غير صحيحة'); else {$c=$pdo->prepare('SELECT COUNT(*) FROM appointments WHERE branch_id=? AND booking_date=? AND slot_time=? AND status="booked"');$c->execute([$p['branch_id'],$p['booking_date'],$p['slot_time']]); if((int)$c->fetchColumn()>=3) flash('err','الشريحة ممتلئة'); else {$to=date('H:i',strtotime($p['slot_time'].' +'.$cfg['interval_minutes'].' minutes'));$pdo->prepare('INSERT INTO appointments (transfer_number,branch_id,company_id,day_name,booking_date,slot_time,slot_to,phone,full_name,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,"booked",NOW())')->execute([$p['transfer_number'],$p['branch_id'],$p['company_id'],$day,$p['booking_date'],$p['slot_time'],$to,$p['phone'],$p['full_name']]);$pdo->prepare('UPDATE otp_codes SET used=1 WHERE id=?')->execute([$or['id']]);unset($_SESSION['pending']);flash('ok','تم الحجز بنجاح');}}}} header('Location: /');exit;}
$branches=$pdo->query('SELECT id,name FROM branches WHERE active=1 ORDER BY name')->fetchAll();$companies=$pdo->query('SELECT id,name FROM remittance_companies WHERE active=1 ORDER BY name')->fetchAll();$days=[];$slots=[];$bid=(int)($_GET['branch_id']??0);$bdate=$_GET['booking_date']??'';
if($bid){$cfg=$pdo->prepare('SELECT * FROM business_days WHERE branch_id=? AND active=1');$cfg->execute([$bid]);$rows=$cfg->fetchAll();$allowed=array_column($rows,'day_name');for($i=1;$i<=21;$i++){$d=date('Y-m-d',strtotime("+$i day"));if(in_array(date('l',strtotime($d)),$allowed,true)&&!is_holiday($d))$days[]=$d;}if($bdate){$day=date('l',strtotime($bdate));$r=null;foreach($rows as $x){if($x['day_name']===$day)$r=$x;}if($r){$s=strtotime($r['start_time']);$e=strtotime($r['end_time']);$int=(int)$r['interval_minutes']*60;for($t=$s;$t+$int<=$e;$t+=$int){$from=date('H:i',$t);$c=$pdo->prepare('SELECT COUNT(*) FROM appointments WHERE branch_id=? AND booking_date=? AND slot_time=? AND status="booked"');$c->execute([$bid,$bdate,$from]);$slots[]=['time'=>$from,'available'=>(int)$c->fetchColumn()<3];}}}}
$title='الحجز';include __DIR__.'/includes/header.php'; ?>
<div class='card p-3'><form method='get' class='row g-2'><div class='col-md-4'><label class='form-label'>الفرع</label><select class='form-select' name='branch_id' required><option value=''>اختر</option><?php foreach($branches as $b): ?><option value='<?= $b['id'] ?>' <?= $bid===$b['id']?'selected':'' ?>><?= e($b['name']) ?></option><?php endforeach; ?></select></div><div class='col-md-4'><label class='form-label'>التاريخ</label><select class='form-select' name='booking_date' required><?php foreach($days as $d): ?><option value='<?= e($d) ?>' <?= $bdate===$d?'selected':'' ?>><?= e($d) ?></option><?php endforeach; ?></select></div><div class='col-md-4 d-flex align-items-end'><button class='btn btn-dark w-100'>تحميل</button></div></form><hr>
<form method='post' class='row g-2'><input type='hidden' name='<?= e($config['security']['csrf_key']) ?>' value='<?= e(csrf_token()) ?>'><input type='hidden' name='branch_id' value='<?= $bid ?>'><input type='hidden' name='booking_date' value='<?= e($bdate) ?>'><div class='col-md-4'><label class='form-label'>الشركة</label><select class='form-select' name='company_id' required><?php foreach($companies as $c): ?><option value='<?= $c['id'] ?>'><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class='col-md-4'><label class='form-label'>الوقت</label><select class='form-select' name='slot_time' required><?php foreach($slots as $s): if(!$s['available']) continue; ?><option value='<?= e($s['time']) ?>'><?= e($s['time']) ?></option><?php endforeach; ?></select></div><div class='col-md-4'><label class='form-label'>رقم الحوالة</label><input class='form-control' name='transfer_number' required></div><div class='col-md-4'><label class='form-label'>الهاتف</label><input class='form-control' name='phone' required></div><div class='col-md-4'><label class='form-label'>الاسم الثلاثي</label><input class='form-control' name='full_name' required></div><div class='col-md-2'><label class='form-label'>كابتشا</label><input class='form-control' readonly value='<?= e($_SESSION['captcha']) ?>'></div><div class='col-md-2'><label class='form-label'>أدخل</label><input class='form-control' name='captcha' required></div><div class='col-md-4 d-flex align-items-end gap-2'><button class='btn btn-primary w-100' name='send_otp' value='1'>إرسال OTP</button><button class='btn btn-outline-secondary w-100' name='refresh_captcha' value='1'>تحديث</button></div></form>
<?php if(!empty($_SESSION['pending'])): ?><hr><form method='post' class='row g-2'><input type='hidden' name='<?= e($config['security']['csrf_key']) ?>' value='<?= e(csrf_token()) ?>'><div class='col-md-4'><input class='form-control' name='otp_code' maxlength='4' placeholder='OTP'></div><div class='col-md-4'><button class='btn btn-success w-100' name='confirm_booking' value='1'>تأكيد الحجز</button></div></form><?php endif; ?></div>
<?php include __DIR__.'/includes/footer.php';
