<?php require_once __DIR__.'/../includes/functions.php'; require_login(['admin','manager']); verify_csrf(); $pdo=db(); $date=$_GET['date']??date('Y-m-d');
if(isset($_POST['generate']) && role()==='admin'){
  $targetDate=$_POST['report_date']??date('Y-m-d');
  $count=generate_daily_reports_if_needed($targetDate);
  $sent=send_daily_reports_emails_if_needed($targetDate);
  flash('ok',"تم توليد $count تقارير وإرسال $sent بريد.");
  header('Location: reports.php?date='.urlencode($targetDate)); exit;
}
$p=[':d'=>$date]; $where=' WHERE a.booking_date=:d AND a.status="booked" '; if(role()==='manager'&&manager_scoped()){$where.=' AND a.branch_id=:b ';$p[':b']=(int)user_branch_id();} $s=$pdo->prepare('SELECT a.full_name,a.phone,a.booking_date,a.slot_time,a.slot_to,b.name branch_name FROM appointments a LEFT JOIN branches b ON b.id=a.branch_id '.$where.' ORDER BY a.branch_id,a.slot_time');$s->execute($p);$rows=$s->fetchAll(); $title='التقارير'; include __DIR__.'/../includes/header.php'; ?>
<div class='card p-3'><a href='dashboard.php' class='btn btn-sm btn-outline-secondary mb-2'>رجوع</a><form method='get' class='row g-2 mb-2'><div class='col-md-3'><input class='form-control' type='date' name='date' value='<?= e($date) ?>'></div><div class='col-md-2'><button class='btn btn-dark w-100'>عرض</button></div></form><?php if(role()==='admin'): ?><form method='post' class='row g-2 mb-3'><input type='hidden' name='<?= e($config['security']['csrf_key']) ?>' value='<?= e(csrf_token()) ?>'><div class='col-md-3'><input class='form-control' type='date' name='report_date' value='<?= e($date) ?>'></div><div class='col-md-3'><button class='btn btn-primary w-100' name='generate' value='1'>توليد/إرسال التقرير اليومي</button></div></form><?php endif; ?><table class='table table-bordered table-sm'><tr><th>الاسم</th><th>الهاتف</th><th>التاريخ</th><th>الوقت</th><th>الفرع</th></tr><?php foreach($rows as $r): ?><tr><td><?= e($r['full_name']) ?></td><td><?= e($r['phone']) ?></td><td><?= e($r['booking_date']) ?></td><td><?= e($r['slot_time'].' - '.$r['slot_to']) ?></td><td><?= e($r['branch_name']) ?></td></tr><?php endforeach; ?></table></div><?php include __DIR__.'/../includes/footer.php';
